### PR TITLE
Increased heap size to 1g

### PR DESCRIPTION
**Pull request by catalin-ilea**

### CODE REVIEW

**Comment by martingartonft** [comment]
lgtm

**Comment by Zapadlo** [comment]
Can we have some background to this?

**Comment by catalin-ilea** [comment]
@Zapadlo The proxy buffers heavily whenever a client is created which tries to process all the messages available in kafka(not the mode our current consumers run). With the current configs it will buffer up to 170MB which with a heap size of 256MB will  cause the proxy to run OOM.  I'm looking at reducing the buffer size but this change should make the proxy run properly until then.

**Comment by martingartonft** [comment]
i think if upstream allowed specifiying a message limit (provided by the consumer at request time ideally) we would revert this.  But until and unless that happens, we're gonna need more ram.

**Comment by Zapadlo** [comment]
Cool +1

**Pull request merged**
